version: '3'

services:
  2g-scraper:
    build: .
    command: npm run 2g-scraper
    volumes:
      - ./logs:/app/logs

  nfs-scraper:
    build: .
    command: npm run nfs-scraper
    volumes:
      - ./logs:/app/logs

  mock-server:
    build: .
    command: npm run mock-server
    ports:
      - 10015:8080
