version: '3'

services:
  scraper:
    build: .
    command: npm start
    volumes:
      - ./logs:/app/logs

  mock-server:
    build: .
    command: npm run mock-server
    ports:
      - 10015:8080
